;;; tinygo-test.el --- Tests for tinygo.el -*- lexical-binding: t; -*-

(require 'ert)
(require 'cl-lib)
(require 'tinygo)

(defvar lsp-mode nil)

(ert-deftest tinygo-info-value-parses-info-output ()
  (let ((info "GOOS:              linux\nGOARCH:            arm\nbuild tags:        avr baremetal tinygo\ncached GOROOT:     /tmp/tinygo\n"))
    (should (equal (tinygo--info-value "GOOS" info) "linux"))
    (should (equal (tinygo--info-value "GOARCH" info) "arm"))
    (should (equal (tinygo--info-value "build tags" info) "avr baremetal tinygo"))
    (should (equal (tinygo--info-value "cached GOROOT" info) "/tmp/tinygo"))))

(ert-deftest tinygo-environment-uses-tinygo-info ()
  (let ((tinygo--environment-cache (make-hash-table :test #'equal))
        (tinygo-command "tinygo"))
    (cl-letf (((symbol-function 'tinygo--info)
               (lambda (_) "GOOS: linux\nGOARCH: arm\nbuild tags: one two\ncached GOROOT: /tmp/root\n")))
      (should (equal (tinygo--environment-for-target "arduino")
                     '("GOROOT=/tmp/root" "GOOS=linux" "GOARCH=arm"
                       "GOFLAGS=-tags=one,two"))))))

(ert-deftest tinygo-server-command-wraps-configured-server ()
  (let ((tinygo-lsp-server-command '("gopls" "-remote=auto")))
    (cl-letf (((symbol-function 'tinygo-current-target) (lambda () "pico"))
              ((symbol-function 'tinygo--environment-for-target)
               (lambda (_) '("GOROOT=/tmp/root" "GOOS=linux"))))
      (should (equal (tinygo--server-command)
                     '("env" "GOROOT=/tmp/root" "GOOS=linux" "gopls" "-remote=auto"))))))

(ert-deftest tinygo-eglot-contact-accepts-eglot-context-arguments ()
  (cl-letf (((symbol-function 'tinygo--server-command)
             (lambda () '("env" "GOOS=linux" "gopls"))))
    (should (equal (tinygo--eglot-contact nil 'project)
                   '("env" "GOOS=linux" "gopls")))))

(ert-deftest tinygo-set-target-validates-and-restarts-eglot ()
  (let ((tinygo--project-targets (make-hash-table :test #'equal))
        (validated nil)
        (shutdown nil)
        (started nil))
    (cl-letf (((symbol-function 'tinygo--project-key) (lambda (&optional _) "/project/"))
              ((symbol-function 'tinygo--environment-for-target)
               (lambda (target) (setq validated target) '("GOOS=linux")))
              ((symbol-function 'tinygo--set-project-target)
               (lambda (target) (puthash "/project/" target tinygo--project-targets)))
              ((symbol-function 'eglot-current-server) (lambda () 'server))
              ((symbol-function 'eglot-shutdown) (lambda (server) (setq shutdown server)))
              ((symbol-function 'tinygo-eglot-ensure) (lambda () (setq started t))))
      (tinygo-set-target "  pico  ")
      (should (equal validated "pico"))
      (should (equal (gethash "/project/" tinygo--project-targets) "pico"))
      (should (eq shutdown 'server))
      (should started))))

(ert-deftest tinygo-restart-passes-each-lsp-mode-workspace ()
  (let ((restarted nil))
    (cl-letf (((symbol-value 'lsp-mode) t)
              ((symbol-function 'eglot-current-server) (lambda () nil))
              ((symbol-function 'lsp-workspaces) (lambda () '(one two)))
              ((symbol-function 'lsp-workspace-restart)
               (lambda (workspace) (push workspace restarted))))
      (should (eq (tinygo--restart-active-lsp) 'lsp-mode))
      (should (equal (nreverse restarted) '(one two))))))

(ert-deftest tinygo-project-selection-overrides-target-file ()
  (let ((tinygo--project-targets (make-hash-table :test #'equal))
        (tinygo-target nil))
    (puthash "/project/" "pico" tinygo--project-targets)
    (cl-letf (((symbol-function 'tinygo--project-key) (lambda (&optional _) "/project/"))
              ((symbol-function 'tinygo--file-target) (lambda (_) "arduino")))
      (should (equal (tinygo-current-target "/project/src/") "pico")))))

(ert-deftest tinygo-ensure-honors-explicit-client-selection ()
  (let ((tinygo-lsp-client 'eglot)
        (started nil))
    (cl-letf (((symbol-function 'tinygo-eglot-ensure)
               (lambda () (setq started 'eglot)))
              ((symbol-function 'tinygo-lsp-ensure)
               (lambda () (setq started 'lsp-mode))))
      (tinygo-ensure)
      (should (eq started 'eglot)))))

(ert-deftest tinygo-ensure-auto-respects-active-lsp-mode ()
  (let ((tinygo-lsp-client 'auto)
        (started nil))
    (cl-letf (((symbol-value 'lsp-mode) t)
              ((symbol-function 'eglot-current-server) (lambda () nil))
              ((symbol-function 'tinygo-eglot-ensure)
               (lambda () (setq started 'eglot)))
              ((symbol-function 'tinygo-lsp-ensure)
               (lambda () (setq started 'lsp-mode))))
      (tinygo-ensure)
      (should (eq started 'lsp-mode)))))

(ert-deftest tinygo-auto-ensure-starts-only-marked-projects ()
  (let ((tinygo-auto-start t)
        (marked t)
        (validated nil)
        (started 0))
    (cl-letf (((symbol-function 'tinygo-project-p) (lambda (&optional _) marked))
              ((symbol-function 'tinygo-current-target) (lambda (&optional _) "pico"))
              ((symbol-function 'tinygo--environment-for-target)
               (lambda (target) (setq validated target)))
              ((symbol-function 'tinygo-ensure)
               (lambda () (setq started (1+ started)))))
      (tinygo-auto-ensure)
      (should (equal validated "pico"))
      (should (= started 1))
      (setq marked nil
            validated nil)
      (tinygo-auto-ensure)
      (should-not validated)
      (should (= started 1)))))

(ert-deftest tinygo-installs-automatic-go-hooks ()
  (should (memq #'tinygo-auto-ensure go-mode-hook))
  (should (memq #'tinygo-auto-ensure go-ts-mode-hook)))

(ert-deftest tinygo-project-p-finds-parent-target-marker ()
  (let* ((root (make-temp-file "tinygo-project-" t))
         (child (expand-file-name "cmd/blink" root)))
    (unwind-protect
        (progn
          (make-directory child t)
          (with-temp-file (expand-file-name ".tinygo-target" root)
            (insert "pico\n"))
          (should (tinygo-project-p child)))
      (delete-directory root t))))

;;; tinygo-test.el ends here
