;;; tinygo.el --- TinyGo environments for Emacs LSP clients -*- lexical-binding: t; -*-

;; Copyright (C) 2026
;; SPDX-License-Identifier: MIT

;; Author: TinyGo Emacs contributors
;; Version: 0.2.0
;; Package-Requires: ((emacs "27.1"))
;; Keywords: languages, tools, go, tinygo

;; This file is not part of GNU Emacs.

;;; Commentary:
;;
;; TinyGo uses the Go language server (normally gopls) with an environment
;; generated by `tinygo info TARGET'.  This package creates that environment
;; and gives it to Eglot or lsp-mode.  It deliberately does not implement a
;; second completion engine: completion, diagnostics, navigation and refactors
;; remain the responsibility of the user's usual Go LSP server and UI.

;;; Code:

(require 'cl-lib)
(require 'subr-x)

(declare-function lsp-register-client "lsp-mode")
(declare-function make-lsp-client "lsp-mode")
(declare-function lsp-stdio-connection "lsp-mode")
(declare-function lsp-deferred "lsp-mode")
(declare-function lsp-workspaces "lsp-mode")
(declare-function lsp-workspace-restart "lsp-mode")
(declare-function eglot-current-server "eglot")
(declare-function eglot-shutdown "eglot")

(defvar lsp-mode)

(defgroup tinygo nil
  "TinyGo support for Emacs."
  :group 'languages)

(defcustom tinygo-command "tinygo"
  "The TinyGo executable."
  :type 'string
  :group 'tinygo)

(defcustom tinygo-target nil
  "TinyGo target for the current project.

Set this in `.dir-locals.el', set it buffer-locally, or put the target name in
a `.tinygo-target' file at the project root.  A buffer-local or directory-local
value takes precedence over the file."
  :type '(choice (const :tag "Read .tinygo-target" nil) string)
  :safe #'stringp
  :group 'tinygo)

(defcustom tinygo-lsp-server-command '("gopls")
  "Command used as the Go language server.

The command receives the TinyGo environment before it is executed.  Thus this
also supports compatible alternatives to gopls.  The command must speak LSP
over standard input and output."
  :type '(repeat string)
  :group 'tinygo)

(defcustom tinygo-lsp-client 'auto
  "LSP client used by `tinygo-ensure'.

With the default value `auto', prefer Eglot when it is available and use
lsp-mode otherwise.  Set this to `eglot' or `lsp-mode' to choose explicitly."
  :type '(choice (const :tag "Automatically select" auto)
                 (const :tag "Eglot" eglot)
                 (const :tag "lsp-mode" lsp-mode))
  :group 'tinygo)

(defcustom tinygo-auto-start t
  "Whether to start TinyGo LSP support when `.tinygo-target' is present.

When non-nil, opening a Go buffer below a `.tinygo-target' file validates the
configured target and calls `tinygo-ensure'.  Ordinary Go projects are not
affected."
  :type 'boolean
  :group 'tinygo)

(defcustom tinygo-disabled-flycheck-checkers
  '(go-build go-test go-vet go-errcheck go-unconvert go-staticcheck golangci-lint)
  "Flycheck checkers disabled in TinyGo buffers.

These drive the host Go toolchain, which cannot analyse TinyGo code: it
resolves the host GOROOT rather than TinyGo's, lacks the target's build
tags, and rejects `#cgo' flags that TinyGo libraries rely on -- espradio
trips the last of these with `-fno-short-enums'.  What they report is
therefore noise about the toolchain rather than about the code, and
disabling one only promotes the next in the chain.  Diagnostics still
come from the language server, which does get TinyGo's environment.

`go-gofmt' is deliberately absent: formatting does not depend on any of
this.  Set to nil to leave Flycheck alone entirely."
  :type '(repeat symbol)
  :group 'tinygo)

(defvar flycheck-disabled-checkers)

(defvar tinygo--environment-cache (make-hash-table :test #'equal)
  "Cache of environments keyed by TinyGo executable and target.")

(defvar tinygo--project-targets (make-hash-table :test #'equal)
  "Targets selected interactively, keyed by project directory.")

(defun tinygo--project-key (&optional directory)
  "Return a stable TinyGo project key for DIRECTORY."
  (let ((directory (or directory default-directory)))
    (file-truename
     (or (locate-dominating-file directory ".tinygo-target")
         (locate-dominating-file directory "go.work")
         (locate-dominating-file directory "go.mod")
         (locate-dominating-file directory ".git")
         directory))))

(defun tinygo--file-target (directory)
  "Return the target configured by `.tinygo-target' above DIRECTORY."
  (when-let ((file (locate-dominating-file directory ".tinygo-target")))
    (with-temp-buffer
      (insert-file-contents (expand-file-name ".tinygo-target" file))
      (string-trim (buffer-substring-no-properties (point-min) (point-max))))))

(defun tinygo-project-p (&optional directory)
  "Return non-nil when DIRECTORY is below a `.tinygo-target' file."
  (and (locate-dominating-file (or directory default-directory)
                              ".tinygo-target")
       t))

(defun tinygo--configured-target (&optional directory)
  "Return the target configured for DIRECTORY's project, or nil.

Only project-scoped sources count: a buffer-local or directory-local
`tinygo-target', a target chosen with `tinygo-set-target', or a
`.tinygo-target' file.  The global value of `tinygo-target' is
deliberately excluded -- it says nothing about whether a given project is
a TinyGo project, and treating it as if it did makes every ordinary Go
project look like one."
  (let ((directory (or directory default-directory)))
    (or (and (local-variable-p 'tinygo-target) tinygo-target)
        (gethash (tinygo--project-key directory) tinygo--project-targets)
        (tinygo--file-target directory))))

(defun tinygo-target-configured-p (&optional directory)
  "Return non-nil when DIRECTORY belongs to a project with a TinyGo target."
  (let ((target (tinygo--configured-target directory)))
    (and (stringp target) (not (string-empty-p target)))))

(defun tinygo-current-target (&optional directory)
  "Return the TinyGo target for DIRECTORY, or signal a helpful error.

Falls back to the global value of `tinygo-target' so that explicit
commands still work when one is set.  Code deciding whether to activate
TinyGo support at all must use `tinygo-target-configured-p' instead."
  (let ((target (or (tinygo--configured-target directory)
                    (default-value 'tinygo-target))))
    (unless (and (stringp target) (not (string-empty-p target)))
      (user-error "No TinyGo target: set tinygo-target or add .tinygo-target"))
    target))

(defun tinygo--pin-target (target)
  "Record TARGET buffer-locally so later lookups cannot lose it.

Targets are normally resolved from `default-directory', but the functions
supplying the server command and its environment run long after a buffer
asks for a server: lsp-mode defers startup through a timer, and binds
`default-directory' to the workspace root before calling them.  That root
is frequently a repository root sitting above the directory that holds
`.tinygo-target' -- a Go module under examples/ is the ordinary case --
so resolution failed there with a \"No TinyGo target\" error raised
inside a timer, where it reads as unrelated to opening the file.

Pinning the resolved value makes those later lookups independent of the
directory: a buffer-local `tinygo-target' is the first source consulted
by `tinygo--configured-target'.  It stays buffer-local, so it cannot
widen activation for any other buffer."
  (setq-local tinygo-target target))

(defun tinygo--info (target)
  "Return the output of `tinygo info TARGET', or signal an error."
  (unless (executable-find tinygo-command)
    (user-error "Cannot find TinyGo executable: %s" tinygo-command))
  (with-temp-buffer
    (let ((status (process-file tinygo-command nil (current-buffer) nil "info" target)))
      (unless (zerop status)
        (user-error "TinyGo info %s failed: %s" target
                    (string-trim (buffer-string))))
      (buffer-string))))

(defun tinygo--info-value (label info)
  "Extract LABEL's value from TinyGo INFO output.

The separator is matched with `[[:blank:]]' rather than a hand-written
class.  Writing \"[ \\t]\" in Emacs Lisp produces the three characters
space, backslash and the letter t, so a value beginning with that letter
-- such as the `tinygo.wasm' and `tinygo.riscv' build tags -- silently
lost its first character."
  (when (string-match (format "^%s:[[:blank:]]*\\(.+\\)$" (regexp-quote label)) info)
    (string-trim (match-string 1 info))))

(defun tinygo--environment-for-target (target)
  "Return environment variables required for TARGET's Go language server.

GOROOT and the build tags are required: they are what TinyGo's IDE
guidance specifies, and without them the `machine' package cannot
resolve.  GOOS and GOARCH are passed on when `tinygo info' reports them,
but their absence is not fatal, so a TinyGo release that changes or drops
those lines degrades instead of refusing to start.

Note that the reported GOARCH is a proxy rather than the literal
architecture -- TinyGo reports `arm' for AVR and 32-bit RISC-V alike,
because Go has no such GOARCH and rejects the pair outright.  Passing it
is still worthwhile: it makes the server analyse with the same word size
TinyGo compiles for, where omitting it would silently assume the 64-bit
host.

CGO_ENABLED is forced on because passing GOARCH is what makes this look
like a cross-build to Go, which disables cgo by default.  Cgo files are
then dropped from every package, so a library binding C -- espradio, for
one, whose Enable, Connect and Scan all live in a cgo file -- reports its
whole API as undefined while GOROOT and the build tags look correct.  The
server only parses, so no C cross-compiler is needed for this to help."
  (or (gethash (list tinygo-command target) tinygo--environment-cache)
      (let* ((info (tinygo--info target))
             (goroot (tinygo--info-value "cached GOROOT" info))
             (goos (tinygo--info-value "GOOS" info))
             (goarch (tinygo--info-value "GOARCH" info))
             (tags (tinygo--info-value "build tags" info)))
        (unless (and goroot tags)
          (user-error "Could not read GOROOT and build tags for TinyGo target %s"
                      target))
        (let ((environment
               (delq nil
                     (list (concat "GOROOT=" goroot)
                           (and goos (concat "GOOS=" goos))
                           (and goarch (concat "GOARCH=" goarch))
                           "CGO_ENABLED=1"
                           (concat "GOFLAGS=-tags="
                                   (replace-regexp-in-string " +" "," tags))))))
          (puthash (list tinygo-command target) environment tinygo--environment-cache)
          environment))))

(defun tinygo-clear-environment-cache ()
  "Forget cached output from `tinygo info'."
  (interactive)
  (clrhash tinygo--environment-cache)
  (message "TinyGo environment cache cleared"))

(defun tinygo-environment-alist (&optional target)
  "Return TARGET's environment as an alist of (NAME . VALUE)."
  (mapcar (lambda (entry)
            (let ((split (string-search "=" entry)))
              (cons (substring entry 0 split) (substring entry (1+ split)))))
          (tinygo--environment-for-target (or target (tinygo-current-target)))))

(defun tinygo--env-wrapper-available-p ()
  "Return non-nil when the POSIX `env' command can be used as a wrapper."
  (and (not (memq system-type '(ms-dos windows-nt)))
       (executable-find "env")
       t))

(defun tinygo--server-command ()
  "Return the LSP server command for the current TinyGo buffer.

Where a POSIX `env' is available the environment is carried in the
command itself, which keeps it attached to this server no matter how the
client spawns it.  Elsewhere -- notably Windows -- the command is
returned bare and the caller is responsible for binding
`process-environment'; see `tinygo--with-environment'."
  (if (tinygo--env-wrapper-available-p)
      (append (list "env")
              (tinygo--environment-for-target (tinygo-current-target))
              tinygo-lsp-server-command)
    tinygo-lsp-server-command))

(defmacro tinygo--with-environment (target &rest body)
  "Evaluate BODY with TARGET's TinyGo environment in `process-environment'."
  (declare (indent 1) (debug t))
  `(let ((process-environment
          (append (tinygo--environment-for-target ,target) process-environment)))
     ,@body))

(defun tinygo--set-project-target (target)
  "Set TARGET for the current project and its open Go buffers."
  (let ((project-key (tinygo--project-key)))
    (puthash project-key target tinygo--project-targets)
    (dolist (buffer (buffer-list))
      (with-current-buffer buffer
        (when (and (derived-mode-p 'go-mode 'go-ts-mode)
                   (equal (ignore-errors (tinygo--project-key)) project-key))
          (setq-local tinygo-target target))))))

(defun tinygo--restart-active-lsp ()
  "Restart the active Eglot or lsp-mode server with fresh TinyGo settings."
  (let ((eglot-server
         (and (fboundp 'eglot-current-server)
              (ignore-errors (eglot-current-server)))))
    (cond
     (eglot-server
      ;; `eglot-reconnect' deliberately reuses the original process command.
      ;; Shut down and start anew so a changed target gets a new environment.
      (eglot-shutdown eglot-server)
      (tinygo-eglot-ensure)
      'eglot)
     ((and (boundp 'lsp-mode)
           (symbol-value 'lsp-mode)
           (fboundp 'lsp-workspaces)
           (fboundp 'lsp-workspace-restart))
      (let ((workspaces (lsp-workspaces)))
        (dolist (workspace workspaces)
          (lsp-workspace-restart workspace))
        (and workspaces 'lsp-mode))))))

;;;###autoload
(defun tinygo-set-target (target)
  "Validate and select TARGET, then restart the active LSP workspace."
  (interactive
   (list
    (read-string "TinyGo target: "
                 (condition-case nil
                     (tinygo-current-target)
                   (user-error nil)))))
  (setq target (string-trim target))
  (when (string-empty-p target)
    (user-error "TinyGo target cannot be empty"))
  ;; Validate before changing buffer or project state.  This also warms the
  ;; environment cache used when the new language-server process starts.
  (remhash (list tinygo-command target) tinygo--environment-cache)
  (tinygo--environment-for-target target)
  (tinygo--set-project-target target)
  (tinygo--restart-active-lsp)
  (message "TinyGo target set to %s" target))

;;; Eglot

(defun tinygo--eglot-contact (&optional _interactive _project)
  "Return the Eglot contact for the current TinyGo buffer."
  (tinygo--server-command))

;;;###autoload
(defun tinygo-eglot-ensure ()
  "Start Eglot for this buffer with its existing Go LSP under TinyGo.
This is buffer-local and never changes Eglot's normal Go configuration."
  (interactive)
  (let ((target (tinygo-current-target)))
    (tinygo--pin-target target)
    (require 'eglot)
    ;; Put the local entry first; Eglot uses the first matching association.
    (setq-local eglot-server-programs
                (cons `((go-mode go-ts-mode) . tinygo--eglot-contact)
                      (cl-remove-if
                       (lambda (entry)
                         (eq (cdr-safe entry) 'tinygo--eglot-contact))
                       (copy-tree eglot-server-programs))))
    ;; On POSIX the environment travels inside the command, so this binding
    ;; is redundant but harmless.  Without an `env' wrapper it is the only
    ;; thing that gets the environment to the server, since Eglot spawns it
    ;; with `make-process', which reads the ambient `process-environment'.
    (tinygo--with-environment target
      (eglot-ensure))))

;;; lsp-mode

(defvar tinygo--lsp-mode-client-registered nil)

(defun tinygo--lsp-mode-activate-p (&rest _ignored)
  "Return non-nil if the current buffer belongs to a TinyGo project.

This client outranks lsp-mode's ordinary Go client, so it must only claim
buffers whose project actually selected a target.  A global
`tinygo-target' does not qualify; see `tinygo--configured-target'."
  (tinygo-target-configured-p))

(defun tinygo-register-lsp-mode-client ()
  "Register the TinyGo client with lsp-mode.
This registration is safe to call repeatedly."
  (require 'lsp-mode)
  (unless tinygo--lsp-mode-client-registered
    (lsp-register-client
     (make-lsp-client
      :new-connection (lsp-stdio-connection #'tinygo--server-command)
      ;; lsp-mode's own way of giving a server extra environment; it works
      ;; on every platform, unlike an `env' prefix.
      :environment-fn #'tinygo-environment-alist
      :activation-fn #'tinygo--lsp-mode-activate-p
      :priority 10
      :server-id 'tinygo))
    (setq tinygo--lsp-mode-client-registered t)))

;;;###autoload
(defun tinygo-lsp-ensure ()
  "Start lsp-mode for this buffer with its existing Go LSP under TinyGo."
  (interactive)
  (tinygo--pin-target (tinygo-current-target))
  (tinygo-register-lsp-mode-client)
  (lsp-deferred))

(defun tinygo--disable-host-go-checkers ()
  "Disable Flycheck checkers that cannot analyse TinyGo code.
Does nothing when Flycheck is absent.  See
`tinygo-disabled-flycheck-checkers'."
  (when (and tinygo-disabled-flycheck-checkers
             (boundp 'flycheck-disabled-checkers))
    (setq-local flycheck-disabled-checkers
                (delete-dups
                 (append tinygo-disabled-flycheck-checkers
                         flycheck-disabled-checkers)))))

;;;###autoload
(defun tinygo-ensure ()
  "Start the configured LSP client for the current TinyGo buffer.
The client is chosen by `tinygo-lsp-client'."
  (interactive)
  (tinygo--disable-host-go-checkers)
  (pcase tinygo-lsp-client
    ('eglot (tinygo-eglot-ensure))
    ('lsp-mode (tinygo-lsp-ensure))
    ('auto
     (cond
      ((and (fboundp 'eglot-current-server)
            (ignore-errors (eglot-current-server)))
       (tinygo-eglot-ensure))
      ((and (boundp 'lsp-mode) (symbol-value 'lsp-mode))
       (tinygo-lsp-ensure))
      ((featurep 'lsp-mode)
       (tinygo-lsp-ensure))
      ((require 'eglot nil t)
       (tinygo-eglot-ensure))
      ((require 'lsp-mode nil t)
       (tinygo-lsp-ensure))
      (t
       (user-error "Install Eglot or lsp-mode to use TinyGo LSP support"))))))

;;;###autoload
(defun tinygo-auto-ensure ()
  "Start TinyGo support when the current project has `.tinygo-target'."
  (when (and tinygo-auto-start (tinygo-project-p))
    (condition-case err
        (progn
          ;; Validate now even when the selected client starts asynchronously.
          (tinygo--environment-for-target (tinygo-current-target))
          (tinygo-ensure))
      (error
       (display-warning 'tinygo
                        (format "Automatic TinyGo LSP startup failed: %s"
                                (error-message-string err))
                        :warning)))))

;; Requiring the package is enough to opt in.  Each hook immediately returns
;; in ordinary Go projects without a `.tinygo-target' marker.
(add-hook 'go-mode-hook #'tinygo-auto-ensure)
(add-hook 'go-ts-mode-hook #'tinygo-auto-ensure)

(provide 'tinygo)
;;; tinygo.el ends here
