;;; tinygo.el --- TinyGo environments for Emacs LSP clients -*- lexical-binding: t; -*-

;; Copyright (C) 2026
;; SPDX-License-Identifier: MIT

;; Author: TinyGo Emacs contributors
;; Version: 0.2.0
;; Package-Requires: ((emacs "27.1"))
;; Keywords: languages, tools, go, tinygo

;; This file is not part of GNU Emacs.

;;; Commentary:
;;
;; TinyGo uses the Go language server (normally gopls) with an environment
;; generated by `tinygo info TARGET'.  This package creates that environment
;; and gives it to Eglot or lsp-mode.  It deliberately does not implement a
;; second completion engine: completion, diagnostics, navigation and refactors
;; remain the responsibility of the user's usual Go LSP server and UI.

;;; Code:

(require 'cl-lib)
(require 'subr-x)

(declare-function lsp-register-client "lsp-mode")
(declare-function make-lsp-client "lsp-mode")
(declare-function lsp-stdio-connection "lsp-mode")
(declare-function lsp-deferred "lsp-mode")
(declare-function lsp-workspaces "lsp-mode")
(declare-function lsp-workspace-restart "lsp-mode")
(declare-function eglot-current-server "eglot")
(declare-function eglot-shutdown "eglot")

(defvar lsp-mode)

(defgroup tinygo nil
  "TinyGo support for Emacs."
  :group 'languages)

(defcustom tinygo-command "tinygo"
  "The TinyGo executable."
  :type 'string
  :group 'tinygo)

(defcustom tinygo-target nil
  "TinyGo target for the current project.

Set this in `.dir-locals.el', set it buffer-locally, or put the target name in
a `.tinygo-target' file at the project root.  A buffer-local or directory-local
value takes precedence over the file."
  :type '(choice (const :tag "Read .tinygo-target" nil) string)
  :safe #'stringp
  :group 'tinygo)

(defcustom tinygo-lsp-server-command '("gopls")
  "Command used as the Go language server.

The command receives the TinyGo environment before it is executed.  Thus this
also supports compatible alternatives to gopls.  The command must speak LSP
over standard input and output."
  :type '(repeat string)
  :group 'tinygo)

(defcustom tinygo-lsp-client 'auto
  "LSP client used by `tinygo-ensure'.

With the default value `auto', prefer Eglot when it is available and use
lsp-mode otherwise.  Set this to `eglot' or `lsp-mode' to choose explicitly."
  :type '(choice (const :tag "Automatically select" auto)
                 (const :tag "Eglot" eglot)
                 (const :tag "lsp-mode" lsp-mode))
  :group 'tinygo)

(defcustom tinygo-auto-start t
  "Whether to start TinyGo LSP support when `.tinygo-target' is present.

When non-nil, opening a Go buffer below a `.tinygo-target' file validates the
configured target and calls `tinygo-ensure'.  Ordinary Go projects are not
affected."
  :type 'boolean
  :group 'tinygo)

(defvar tinygo--environment-cache (make-hash-table :test #'equal)
  "Cache of environments keyed by TinyGo executable and target.")

(defvar tinygo--project-targets (make-hash-table :test #'equal)
  "Targets selected interactively, keyed by project directory.")

(defun tinygo--project-key (&optional directory)
  "Return a stable TinyGo project key for DIRECTORY."
  (let ((directory (or directory default-directory)))
    (file-truename
     (or (locate-dominating-file directory ".tinygo-target")
         (locate-dominating-file directory "go.work")
         (locate-dominating-file directory "go.mod")
         (locate-dominating-file directory ".git")
         directory))))

(defun tinygo--file-target (directory)
  "Return the target configured by `.tinygo-target' above DIRECTORY."
  (when-let ((file (locate-dominating-file directory ".tinygo-target")))
    (with-temp-buffer
      (insert-file-contents (expand-file-name ".tinygo-target" file))
      (string-trim (buffer-substring-no-properties (point-min) (point-max))))))

(defun tinygo-project-p (&optional directory)
  "Return non-nil when DIRECTORY is below a `.tinygo-target' file."
  (and (locate-dominating-file (or directory default-directory)
                              ".tinygo-target")
       t))

(defun tinygo-current-target (&optional directory)
  "Return the TinyGo target for DIRECTORY, or signal a helpful error."
  (let* ((directory (or directory default-directory))
         (target
          (or (and (local-variable-p 'tinygo-target) tinygo-target)
              (gethash (tinygo--project-key directory) tinygo--project-targets)
              (tinygo--file-target directory)
              (default-value 'tinygo-target))))
    (unless (and (stringp target) (not (string-empty-p target)))
      (user-error "No TinyGo target: set tinygo-target or add .tinygo-target"))
    target))

(defun tinygo--info (target)
  "Return the output of `tinygo info TARGET', or signal an error."
  (unless (executable-find tinygo-command)
    (user-error "Cannot find TinyGo executable: %s" tinygo-command))
  (with-temp-buffer
    (let ((status (process-file tinygo-command nil (current-buffer) nil "info" target)))
      (unless (zerop status)
        (user-error "TinyGo info %s failed: %s" target
                    (string-trim (buffer-string))))
      (buffer-string))))

(defun tinygo--info-value (label info)
  "Extract LABEL's value from TinyGo INFO output."
  (when (string-match (format "^%s:[ \\t]*\\(.+\\)$" (regexp-quote label)) info)
    (string-trim (match-string 1 info))))

(defun tinygo--environment-for-target (target)
  "Return environment variables required for TARGET's Go language server."
  (or (gethash (list tinygo-command target) tinygo--environment-cache)
      (let* ((info (tinygo--info target))
             (goroot (tinygo--info-value "cached GOROOT" info))
             (goos (tinygo--info-value "GOOS" info))
             (goarch (tinygo--info-value "GOARCH" info))
             (tags (tinygo--info-value "build tags" info)))
        (unless (and goroot goos goarch tags)
          (user-error "Could not read TinyGo environment for target %s" target))
        (let ((environment
               (list (concat "GOROOT=" goroot)
                     (concat "GOOS=" goos)
                     (concat "GOARCH=" goarch)
                     (concat "GOFLAGS=-tags=" (replace-regexp-in-string " +" "," tags)))))
          (puthash (list tinygo-command target) environment tinygo--environment-cache)
          environment))))

(defun tinygo-clear-environment-cache ()
  "Forget cached output from `tinygo info'."
  (interactive)
  (clrhash tinygo--environment-cache)
  (message "TinyGo environment cache cleared"))

(defun tinygo--server-command ()
  "Return an LSP command wrapped in TinyGo's target environment.
This is suitable for both Eglot and lsp-mode connection functions."
  (append (list "env")
          (tinygo--environment-for-target (tinygo-current-target))
          tinygo-lsp-server-command))

(defun tinygo--set-project-target (target)
  "Set TARGET for the current project and its open Go buffers."
  (let ((project-key (tinygo--project-key)))
    (puthash project-key target tinygo--project-targets)
    (dolist (buffer (buffer-list))
      (with-current-buffer buffer
        (when (and (derived-mode-p 'go-mode 'go-ts-mode)
                   (equal (ignore-errors (tinygo--project-key)) project-key))
          (setq-local tinygo-target target))))))

(defun tinygo--restart-active-lsp ()
  "Restart the active Eglot or lsp-mode server with fresh TinyGo settings."
  (let ((eglot-server
         (and (fboundp 'eglot-current-server)
              (ignore-errors (eglot-current-server)))))
    (cond
     (eglot-server
      ;; `eglot-reconnect' deliberately reuses the original process command.
      ;; Shut down and start anew so a changed target gets a new environment.
      (eglot-shutdown eglot-server)
      (tinygo-eglot-ensure)
      'eglot)
     ((and (boundp 'lsp-mode)
           (symbol-value 'lsp-mode)
           (fboundp 'lsp-workspaces)
           (fboundp 'lsp-workspace-restart))
      (let ((workspaces (lsp-workspaces)))
        (dolist (workspace workspaces)
          (lsp-workspace-restart workspace))
        (and workspaces 'lsp-mode))))))

;;;###autoload
(defun tinygo-set-target (target)
  "Validate and select TARGET, then restart the active LSP workspace."
  (interactive
   (list
    (read-string "TinyGo target: "
                 (condition-case nil
                     (tinygo-current-target)
                   (user-error nil)))))
  (setq target (string-trim target))
  (when (string-empty-p target)
    (user-error "TinyGo target cannot be empty"))
  ;; Validate before changing buffer or project state.  This also warms the
  ;; environment cache used when the new language-server process starts.
  (remhash (list tinygo-command target) tinygo--environment-cache)
  (tinygo--environment-for-target target)
  (tinygo--set-project-target target)
  (tinygo--restart-active-lsp)
  (message "TinyGo target set to %s" target))

;;; Eglot

(defun tinygo--eglot-contact (&optional _interactive _project)
  "Return the Eglot contact for the current TinyGo buffer."
  (tinygo--server-command))

;;;###autoload
(defun tinygo-eglot-ensure ()
  "Start Eglot for this buffer with its existing Go LSP under TinyGo.
This is buffer-local and never changes Eglot's normal Go configuration."
  (interactive)
  (tinygo-current-target)
  (require 'eglot)
  ;; Put the local entry first; Eglot uses the first matching association.
  (setq-local eglot-server-programs
              (cons `((go-mode go-ts-mode) . tinygo--eglot-contact)
                    (cl-remove-if
                     (lambda (entry)
                       (eq (cdr-safe entry) 'tinygo--eglot-contact))
                     (copy-tree eglot-server-programs))))
  (eglot-ensure))

;;; lsp-mode

(defvar tinygo--lsp-mode-client-registered nil)

(defun tinygo--lsp-mode-activate-p (&rest _ignored)
  "Return non-nil if the current buffer has a TinyGo target."
  (condition-case nil
      (progn (tinygo-current-target) t)
    (user-error nil)))

(defun tinygo-register-lsp-mode-client ()
  "Register the TinyGo client with lsp-mode.
This registration is safe to call repeatedly."
  (require 'lsp-mode)
  (unless tinygo--lsp-mode-client-registered
    (lsp-register-client
     (make-lsp-client
      :new-connection (lsp-stdio-connection #'tinygo--server-command)
      :activation-fn #'tinygo--lsp-mode-activate-p
      :priority 10
      :server-id 'tinygo))
    (setq tinygo--lsp-mode-client-registered t)))

;;;###autoload
(defun tinygo-lsp-ensure ()
  "Start lsp-mode for this buffer with its existing Go LSP under TinyGo."
  (interactive)
  (tinygo-current-target)
  (tinygo-register-lsp-mode-client)
  (lsp-deferred))

;;;###autoload
(defun tinygo-ensure ()
  "Start the configured LSP client for the current TinyGo buffer.
The client is chosen by `tinygo-lsp-client'."
  (interactive)
  (pcase tinygo-lsp-client
    ('eglot (tinygo-eglot-ensure))
    ('lsp-mode (tinygo-lsp-ensure))
    ('auto
     (cond
      ((and (fboundp 'eglot-current-server)
            (ignore-errors (eglot-current-server)))
       (tinygo-eglot-ensure))
      ((and (boundp 'lsp-mode) (symbol-value 'lsp-mode))
       (tinygo-lsp-ensure))
      ((featurep 'lsp-mode)
       (tinygo-lsp-ensure))
      ((require 'eglot nil t)
       (tinygo-eglot-ensure))
      ((require 'lsp-mode nil t)
       (tinygo-lsp-ensure))
      (t
       (user-error "Install Eglot or lsp-mode to use TinyGo LSP support"))))))

;;;###autoload
(defun tinygo-auto-ensure ()
  "Start TinyGo support when the current project has `.tinygo-target'."
  (when (and tinygo-auto-start (tinygo-project-p))
    (condition-case err
        (progn
          ;; Validate now even when the selected client starts asynchronously.
          (tinygo--environment-for-target (tinygo-current-target))
          (tinygo-ensure))
      (error
       (display-warning 'tinygo
                        (format "Automatic TinyGo LSP startup failed: %s"
                                (error-message-string err))
                        :warning)))))

;; Requiring the package is enough to opt in.  Each hook immediately returns
;; in ordinary Go projects without a `.tinygo-target' marker.
(add-hook 'go-mode-hook #'tinygo-auto-ensure)
(add-hook 'go-ts-mode-hook #'tinygo-auto-ensure)

(provide 'tinygo)
;;; tinygo.el ends here
