;;; tinygo.el --- TinyGo environments for Emacs LSP clients -*- lexical-binding: t; -*-

;; Copyright (C) 2026
;; SPDX-License-Identifier: MIT

;; Author: TinyGo Emacs contributors
;; Version: 0.1.0
;; Package-Requires: ((emacs "27.1"))
;; Keywords: languages, tools, go, tinygo

;; This file is not part of GNU Emacs.

;;; Commentary:
;;
;; TinyGo uses the Go language server (normally gopls) with an environment
;; generated by `tinygo info TARGET'.  This package creates that environment
;; and gives it to Eglot or lsp-mode.  It deliberately does not implement a
;; second completion engine: completion, diagnostics, navigation and refactors
;; remain the responsibility of the user's usual Go LSP server and UI.

;;; Code:

(require 'subr-x)

(declare-function lsp-register-client "lsp-mode")
(declare-function make-lsp-client "lsp-mode")
(declare-function lsp-stdio-connection "lsp-mode")
(declare-function lsp-deferred "lsp-mode")

(defgroup tinygo nil
  "TinyGo support for Emacs."
  :group 'languages)

(defcustom tinygo-command "tinygo"
  "The TinyGo executable."
  :type 'string
  :group 'tinygo)

(defcustom tinygo-target nil
  "TinyGo target for the current project.

Set this in `.dir-locals.el', set it buffer-locally, or put the target name in
a `.tinygo-target' file at the project root.  A buffer-local or directory-local
value takes precedence over the file."
  :type '(choice (const :tag "Read .tinygo-target" nil) string)
  :safe #'stringp
  :group 'tinygo)

(defcustom tinygo-lsp-server-command '("gopls")
  "Command used as the Go language server.

The command receives the TinyGo environment before it is executed.  Thus this
also supports compatible alternatives to gopls.  The command must speak LSP
over standard input and output."
  :type '(repeat string)
  :group 'tinygo)

(defcustom tinygo-lsp-client 'auto
  "LSP client used by `tinygo-ensure'.

With the default value `auto', prefer Eglot when it is available and use
lsp-mode otherwise.  Set this to `eglot' or `lsp-mode' to choose explicitly."
  :type '(choice (const :tag "Automatically select" auto)
                 (const :tag "Eglot" eglot)
                 (const :tag "lsp-mode" lsp-mode))
  :group 'tinygo)

(defvar tinygo--environment-cache (make-hash-table :test #'equal)
  "Cache of environments keyed by TinyGo executable and target.")

(defun tinygo--file-target (directory)
  "Return the target configured by `.tinygo-target' above DIRECTORY."
  (when-let ((file (locate-dominating-file directory ".tinygo-target")))
    (with-temp-buffer
      (insert-file-contents (expand-file-name ".tinygo-target" file))
      (string-trim (buffer-substring-no-properties (point-min) (point-max))))))

(defun tinygo-current-target (&optional directory)
  "Return the TinyGo target for DIRECTORY, or signal a helpful error."
  (let ((target (or tinygo-target
                    (tinygo--file-target (or directory default-directory)))))
    (unless (and (stringp target) (not (string-empty-p target)))
      (user-error "No TinyGo target: set tinygo-target or add .tinygo-target"))
    target))

(defun tinygo--info (target)
  "Return the output of `tinygo info TARGET', or signal an error."
  (unless (executable-find tinygo-command)
    (user-error "Cannot find TinyGo executable: %s" tinygo-command))
  (with-temp-buffer
    (let ((status (process-file tinygo-command nil (current-buffer) nil "info" target)))
      (unless (zerop status)
        (user-error "TinyGo info %s failed: %s" target
                    (string-trim (buffer-string))))
      (buffer-string))))

(defun tinygo--info-value (label info)
  "Extract LABEL's value from TinyGo INFO output."
  (when (string-match (format "^%s:[ \\t]*\\(.+\\)$" (regexp-quote label)) info)
    (string-trim (match-string 1 info))))

(defun tinygo--environment-for-target (target)
  "Return environment variables required for TARGET's Go language server."
  (or (gethash (list tinygo-command target) tinygo--environment-cache)
      (let* ((info (tinygo--info target))
             (goroot (tinygo--info-value "cached GOROOT" info))
             (goos (tinygo--info-value "GOOS" info))
             (goarch (tinygo--info-value "GOARCH" info))
             (tags (tinygo--info-value "build tags" info)))
        (unless (and goroot goos goarch tags)
          (user-error "Could not read TinyGo environment for target %s" target))
        (let ((environment
               (list (concat "GOROOT=" goroot)
                     (concat "GOOS=" goos)
                     (concat "GOARCH=" goarch)
                     (concat "GOFLAGS=-tags=" (replace-regexp-in-string " +" "," tags)))))
          (puthash (list tinygo-command target) environment tinygo--environment-cache)
          environment))))

(defun tinygo-clear-environment-cache ()
  "Forget cached output from `tinygo info'."
  (interactive)
  (clrhash tinygo--environment-cache)
  (message "TinyGo environment cache cleared"))

(defun tinygo--server-command ()
  "Return an LSP command wrapped in TinyGo's target environment.
This is suitable for both Eglot and lsp-mode connection functions."
  (append (list "env")
          (tinygo--environment-for-target (tinygo-current-target))
          tinygo-lsp-server-command))

;;;###autoload
(defun tinygo-set-target (target)
  "Set TARGET for this buffer and restart its LSP workspace when possible."
  (interactive "sTinyGo target: ")
  (setq-local tinygo-target target)
  (tinygo-clear-environment-cache)
  (cond
   ((and (bound-and-true-p eglot--managed-mode) (fboundp 'eglot-reconnect))
    (eglot-reconnect))
   ((and (bound-and-true-p lsp-mode) (fboundp 'lsp-workspace-restart))
    (lsp-workspace-restart)))
  (message "TinyGo target set to %s" target))

;;; Eglot

(defun tinygo--eglot-contact ()
  "Return the Eglot contact for the current TinyGo buffer."
  (tinygo--server-command))

;;;###autoload
(defun tinygo-eglot-ensure ()
  "Start Eglot for this buffer with its existing Go LSP under TinyGo.
This is buffer-local and never changes Eglot's normal Go configuration."
  (interactive)
  (tinygo-current-target)
  (require 'eglot)
  ;; Put the local entry first; Eglot uses the first matching association.
  (setq-local eglot-server-programs
              (cons `((go-mode go-ts-mode) . tinygo--eglot-contact)
                    (copy-tree eglot-server-programs)))
  (eglot-ensure))

;;; lsp-mode

(defvar tinygo--lsp-mode-client-registered nil)

(defun tinygo--lsp-mode-activate-p (&rest _ignored)
  "Return non-nil if the current buffer has a TinyGo target."
  (condition-case nil
      (progn (tinygo-current-target) t)
    (user-error nil)))

(defun tinygo-register-lsp-mode-client ()
  "Register the TinyGo client with lsp-mode.
This registration is safe to call repeatedly."
  (require 'lsp-mode)
  (unless tinygo--lsp-mode-client-registered
    (lsp-register-client
     (make-lsp-client
      :new-connection (lsp-stdio-connection #'tinygo--server-command)
      :activation-fn #'tinygo--lsp-mode-activate-p
      :priority 10
      :server-id 'tinygo))
    (setq tinygo--lsp-mode-client-registered t)))

;;;###autoload
(defun tinygo-lsp-ensure ()
  "Start lsp-mode for this buffer with its existing Go LSP under TinyGo."
  (interactive)
  (tinygo-current-target)
  (tinygo-register-lsp-mode-client)
  (lsp-deferred))

;;;###autoload
(defun tinygo-ensure ()
  "Start the configured LSP client for the current TinyGo buffer.
The client is chosen by `tinygo-lsp-client'."
  (interactive)
  (pcase tinygo-lsp-client
    ('eglot (tinygo-eglot-ensure))
    ('lsp-mode (tinygo-lsp-ensure))
    ('auto
     (if (require 'eglot nil t)
         (tinygo-eglot-ensure)
       (tinygo-lsp-ensure)))))

(provide 'tinygo)
;;; tinygo.el ends here
